# Generated by Django 6.0 on 2026-01-03 19:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('category', models.CharField(choices=[('digital_art', 'Digital Art'), ('photography', 'Photography'), ('graphic_design', 'Graphic Design'), ('illustration', 'Illustration'), ('painting', 'Painting'), ('sculpture', 'Sculpture'), ('animation', 'Animation'), ('video', 'Video Production'), ('music', 'Music'), ('writing', 'Writing'), ('other', 'Other')], max_length=50)),
                ('specialty', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('behance', models.CharField(blank=True, max_length=100)),
                ('dribbble', models.CharField(blank=True, max_length=100)),
                ('youtube', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='artist.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='artist.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('character_design', 'Character Design'), ('concept_art', 'Concept Art'), ('digital_painting', 'Digital Painting'), ('illustration', 'Illustration'), ('graphic_design', 'Graphic Design'), ('photography', 'Photography'), ('animation', 'Animation'), ('ui_ux', 'UI/UX Design'), ('logo_branding', 'Logo & Branding'), ('print_design', 'Print Design'), ('3d_modeling', '3D Modeling'), ('vfx', 'VFX'), ('motion_graphics', 'Motion Graphics'), ('other', 'Other')], max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_images', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('artist_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests', to='artist.artistprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('character_design', 'Character Design'), ('concept_art', 'Concept Art'), ('digital_painting', 'Digital Painting'), ('illustration', 'Illustration'), ('graphic_design', 'Graphic Design'), ('photography', 'Photography'), ('animation', 'Animation'), ('ui_ux', 'UI/UX Design'), ('logo_branding', 'Logo & Branding'), ('print_design', 'Print Design'), ('3d_modeling', '3D Modeling'), ('vfx', 'VFX'), ('motion_graphics', 'Motion Graphics'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='portfolio/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('year_created', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='artist.artistprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='artist.portfolioitem')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artist.artistprofile')),
            ],
            options={
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='ArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='artist.artistprofile')),
            ],
            options={
                'unique_together': {('follower', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artist.portfolioitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'portfolio_item')},
            },
        ),
    ]
