# Generated by Django 6.0 on 2026-01-04 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_type', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('convertible_note', 'Convertible Note'), ('grant', 'Grant'), ('royalty', 'Royalty Agreement'), ('other', 'Other')], max_length=50)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investment_date', models.DateField()),
                ('expected_roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exit_strategy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments_received', to='artist.artistprofile')),
            ],
            options={
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='investor.investment')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('investor_type', models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'Venture Capital'), ('corporate', 'Corporate Investor'), ('family_office', 'Family Office'), ('syndicate', 'Investment Syndicate'), ('crowdfunding', 'Crowdfunding Platform'), ('private_equity', 'Private Equity')], max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('investment_range_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investment_range_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('focus_industries', models.JSONField(blank=True, default=list)),
                ('investment_stages', models.JSONField(blank=True, default=list)),
                ('total_investments', models.PositiveIntegerField(default=0)),
                ('total_portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('successful_exits', models.PositiveIntegerField(default=0)),
                ('avg_ticket_size', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_accepting_pitches', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorFocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='investor.investorprofile')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investor.investorprofile'),
        ),
        migrations.CreateModel(
            name='PitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('executive_summary', models.TextField()),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('market_size', models.TextField(blank=True)),
                ('business_model', models.TextField(blank=True)),
                ('team_description', models.TextField(blank=True)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding_use', models.TextField()),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('equity_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('financial_projections', models.FileField(blank=True, null=True, upload_to='financial_projects/')),
                ('additional_docs', models.FileField(blank=True, null=True, upload_to='pitch_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('accepted', 'Accepted for Meeting'), ('declined', 'Declined'), ('funded', 'Funded'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('investor_notes', models.TextField(blank=True)),
                ('meeting_scheduled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches_made', to='artist.artistprofile')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_requests', to='investor.investorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorArtistInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed Profile'), ('saved', 'Saved for Later'), ('contacted', 'Contacted'), ('pitched', 'Pitched Idea'), ('invested', 'Invested In'), ('followed', 'Followed')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_interactions', to='artist.artistprofile')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_interactions', to='investor.investorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('investor', 'artist', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='InvestorSavedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_investors', to='artist.artistprofile')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_artists', to='investor.investorprofile')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'unique_together': {('investor', 'artist')},
            },
        ),
    ]
